export const REQUEST_SUMMONER_INFO = 'REQUEST_SUMMONER_INFO';
export const GET_SUMMONER_SUCCESS = 'GET_SUMMONER_SUCCESS';
export const GET_SUMMONER_FAILURE = 'GET_SUMMONER_FAILURE'; 
export const REQUEST_ACCOUNT_INFO = 'REQUEST_ACCOUNT_INFO';
export const GET_ACCOUNT_SUCCESS = 'GET_ACCOUNT_SUCCESS';